config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/admin'
  mount API => '/api'

  root to: 'visitors#index'
  devise_for :users
  resources :companies, :shallow => true do
    resources :projects do
      resources :optimizable_classes do
        resources :optimizables do
          resources :optimizable_variants
        end
      end
    end
  end
end

app/controllers/optimizable_classes_controller.rb
class OptimizableClassesController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_project
  after_action :verify_policy_scoped, :only => :index
  after_action :verify_authorized, :except => :index

  def new
    @optimizable_class = @project.optimizable_classes.new
    authorize @optimizable_class
  end

  def create
    @optimizable_class = @project.optimizable_classes.new(optimizable_class_params)
    authorize @optimizable_class

    if @optimizable_class.save
      flash[:notice] = "#{@optimizable_class.name} category successfully created."
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    @optimizable_class = OptimizableClass.find(params[:id])
    authorize @optimizable_class
    deduce_project
  end

  def destroy
    @optimizable_class = OptimizableClass.find(params[:id])
    authorize(@optimizable_class)

    if @optimizable_class.destroy
      flash[:notice] = "#{@optimizable_class.name} category successfully deleted."
    else
      flash[:error] = "An error occurred while attempting to delete the #{@optimizable_class.name} category. "
    end

    redirect_to :back
  end

  protected
  def optimizable_class_params
    params.require(:optimizable_class).permit(:name)
  end

  def deduce_project
    @project = @optimizable_class ? @optimizable_class.project : nil
  end
end

app/helpers/optimizable_classes_helper.rb
module OptimizableClassesHelper
end

app/views/optimizable_classes/new.html.erb
<div class="authform">
  <%= bootstrap_form_for([@project, @optimizable_class], :label_errors => true, :html => { :role => 'form'}) do |f| %>
    <%= f.alert_message "Please fix the errors below." %>

    <h3>New Optimization Category</h3>
    <%= f.text_field :name, :autofocus => true, class: 'form-control' %>

    <%= f.submit 'Create', :class => 'button right' %>
  <% end %>
</div>

app/views/optimizable_classes/show.html.erb
<div class="page-header">
  <h3><%= @optimizable_class.project.name %> - <%= @optimizable_class.name %> <small>Optimization Items</small><%= link_to "+ New Optimization Item", new_optimizable_class_optimizable_path(@optimizable_class), :class => "btn btn-primary pull-right" %></h3>
</div>

<table class="table table-hover">
  <thead>
    <td>Category</td>
    <td>Reference ID</td>
    <td>Description</td>
    <td># variations</td>
    <td></td>
  </thead>
  <% @optimizable_class.optimizables.each do |optimizable| %>
    <tr>
      <td><%= @optimizable_class.name %></td>
      <td><%= link_to optimizable.reference_id, optimizable %></td>
      <td><%= optimizable.description %></td>
      <td><span class="badge"><%= optimizable.optimizable_variants_count %></span></td>
      <td>
        <%= link_to "Edit", edit_optimizable_path(optimizable), :class => "btn btn-primary btn-xs" %>
        <%= link_to "Delete", optimizable, :method => :delete, :class => "btn btn-danger btn-xs", :data => { :confirm => "Are you sure? This action cannot be reversed." } %>
      </td>
    </tr>
  <% end %>
</table>