config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/admin'
  mount API => '/api'

  root to: 'visitors#index'
  devise_for :users
  resources :companies, :shallow => true do
    resources :projects do
      resources :optimizable_classes do
        resources :optimizables do
          resources :optimizable_variants
        end
      end
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company
  has_many :user_permissions, :dependent => :destroy, :as => :restrictable
  has_many :users, :through => :user_permissions
  has_many :optimizable_classes, :dependent => :destroy
  has_many :optimizables, :through => :optimizable_classes
  has_many :optimizable_variants, :through => :optimizables

  validates_uniqueness_of :name, :scope => :company_id, :case_sensitive => false
  validates_uniqueness_of :subdomain, :api_key
  validates_presence_of :name, :subdomain

  before_create :generate_api_key

  private
  def generate_api_key
    begin
      self.api_key = SecureRandom.hex
    end while self.class.exists?(api_key: api_key)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_company
  after_action :verify_policy_scoped, :only => :index
  after_action :verify_authorized, :except => :index

  def new
    @project = @company.projects.new
    authorize @project
  end

  def create
    @project = @company.projects.new(project_params)
    @project.users << current_user
    authorize @project

    if @project.save
      flash[:notice] = "#{@project.name} project successfully created."
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    authorize @project
  end

  protected
  def project_params
    params.require(:project).permit(:name, :subdomain)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/new.html.erb
<div class="authform">
  <%= form_for([@company, @project], :html => { :role => 'form'}) do |f| %>
    <h3>New Project</h3>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :subdomain %>
      <%= f.text_field :subdomain, :autofocus => true, class: 'form-control' %>
    </div>

    <%= f.submit 'Create', :class => 'button right' %>
  <% end %>
</div>

app/views/projects/show.html.erb
<% if @project %>
  <div class="page-header">
    <h3><%= @project.name %> <small>Optimization Categories</small><%= link_to "+ New Optimization Category", new_project_optimizable_class_path(@project), :class => "btn btn-primary pull-right" %></h3>

  </div>
<% end %>

<table class="table table-hover">
  <thead>
    <td>Category</td>
    <td># items</td>
    <td># variations</td>
    <td></td>
  </thead>
  <% @project.optimizable_classes.each do |optimizable_class| %>
    <tr>
      <td><%= link_to optimizable_class.name, optimizable_class %></td>
      <td><span class="badge"><%= optimizable_class.optimizables_count %></span></td>
      <td><span class="badge"><%= optimizable_class.optimizable_variants_count %></span></td>
      <td><%= link_to "Delete", optimizable_class, :method => :delete, :class => "btn btn-danger", :data => { :confirm => "Are you sure? This action cannot be reversed." } %></td>
    </tr>
  <% end %>
</table>