config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/admin'
  mount API => '/api'

  root to: 'visitors#index'
  devise_for :users
  resources :companies, :shallow => true do
    resources :projects do
      resources :optimizable_classes do
        resources :optimizables do
          resources :optimizable_variants
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def find_company
    if params[:company_id].present?
      @company = Company.find(params[:company_id])
    end
  end

  def find_project
    if params[:project_id].present?
      @project = Project.find(params[:project_id])
    end
  end

  def find_optimizable_class
    if params[:optimizable_class_id].present?
      @optimizable_class = OptimizableClass.find(params[:optimizable_class_id])
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name, :companies_attributes => [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/application/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Optim</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= @project && !@project.new_record? ? @project.name : "Projects" %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% current_user.companies.each do |company| %>
                <p><%= company.name %></p>
                <% current_user.projects.each do |project| %>
                  <li><a href="<%= project_path(project) %>"><%= project.name %></a></li>
                <% end %>
                <li class="divider"></li>
                <li><a href="<%= new_company_project_path(company) %>">+ New project</a></li>
              <% end %>
            </ul>
          </li>
        <% end %>
        <li><a href="#">Link</a></li>
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#"><%= link_to 'Edit account', edit_user_registration_path %></a></li>
              <li class="divider"></li>
              <li><a href="#"><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>